apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ehqq46dc0-nodejs 
  janus-idp.io/tekton: ehqq46dc0-nodejs
  backstage.io/kubernetes-id: ehqq46dc0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehqq46dc0-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml